import { AlertTriangle, CheckCircle2, Clock3, History, RotateCcw, X } from 'lucide-react';
import { useEffect } from 'react';
import { ComparisonHistoryItem } from '../../api/client';

export default function ComparisonHistoryDrawer({ open, items, onClose, onOpen, onRerun }: { open: boolean; items: ComparisonHistoryItem[]; onClose: () => void; onOpen: (item: ComparisonHistoryItem) => void; onRerun: (item: ComparisonHistoryItem) => void }) {
  useEffect(() => {
    if (!open) return;
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); };
    window.addEventListener('keydown', closeOnEscape);
    return () => window.removeEventListener('keydown', closeOnEscape);
  }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/20 backdrop-blur-[1px]" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><aside className="h-full w-full max-w-lg overflow-y-auto bg-slate-50 shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="history-title"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-slate-200 bg-white/95 p-5 backdrop-blur"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-indigo-600"><History className="h-3.5 w-3.5" /> Analysis history</div><h2 id="history-title" className="mt-2 text-xl font-semibold text-slate-950">Recent comparisons</h2><p className="mt-1 text-xs text-slate-500">Reopen an analysis or run the same scenarios on current data.</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="Close history"><X className="h-5 w-5" /></button></div><div className="space-y-3 p-4 sm:p-5">{items.map((item) => <article key={item.job_id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><StatusIcon status={item.status} /><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{item.scope}</span>{item.is_stale && <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[9px] font-bold uppercase text-amber-700">Stale</span>}</div><h3 className="mt-2 truncate text-sm font-semibold text-slate-900">{item.baseline_name}</h3><p className="mt-1 line-clamp-2 text-xs text-slate-500">vs {item.candidate_names.join(', ')}</p></div><time className="shrink-0 text-[10px] text-slate-400">{formatDate(item.created_at)}</time></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-[10px] text-slate-400">{item.details_available ? 'Details available' : item.status === 'completed' ? 'Aggregates only' : `${Math.round(item.progress)}% complete`}</span><div className="flex gap-2">{item.status === 'completed' && <button onClick={() => onOpen(item)} className="rounded-md px-2.5 py-1.5 text-xs font-semibold text-indigo-600 hover:bg-indigo-50">Open</button>}<button onClick={() => onRerun(item)} className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-2.5 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50"><RotateCcw className="h-3 w-3" /> Re-run</button></div></div></article>)}{!items.length && <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><History className="mx-auto h-6 w-6 text-slate-300" /><div className="mt-3 text-sm font-medium text-slate-600">No comparisons yet</div><div className="mt-1 text-xs text-slate-400">Your completed analyses will appear here.</div></div>}</div></aside></div>;
}

function StatusIcon({ status }: { status: ComparisonHistoryItem['status'] }) { if (status === 'completed') return <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />; if (status === 'failed' || status === 'cancelled') return <AlertTriangle className="h-3.5 w-3.5 text-rose-500" />; return <Clock3 className="h-3.5 w-3.5 text-indigo-500" />; }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }
